SELECT TABLE1.ID, TABLE1.VALUE1 FROM TABLE1, TABLE2 WHERE 
TABLE2.ID = TABLE1.FKID AND TABLE1.VALUE2 <> 'TEST' 
AND VALUE5 NOT IN (SELECT VALUE FROM TABLE3 WHERE DISCR <> '0') AND VALUE3 = 'VAL' 
AND VALUE4 IN ('VAL','VAL2') AND TABLE1.VALUE1 <> 'TEST2' 
UNION 
SELECT TABLE1.ID, TABLE1.VALUE2 FROM TABLE1, TABLE2 WHERE TABLE2.ID = 
TABLE1.FKID AND TABLE1.VALUE1 = 'TEST2' 
UNION 
SELECT TABLE1.ID, TABLE1.VALUE1 FROM TABLE1, TABLE2 WHERE TABLE2.ID = 
TABLE1.FKID AND TABLE1.VALUE2 = 'TEST' AND TABLE1.VALUE1 <> 'TEST2'
 AND VALUE4 IN ('VAL','VAL2') AND VALUE3 = 'VAL' AND VALUE5 IN (SELECT
 VALUE FROM TABLE3 WHERE DISCR <> '1') ORDER BY 1 ASC
 
 SELECT 
TABLE1.ID, TABLE1.VALUE1 
FROM 
TABLE1, TABLE2 
WHERE TABLE2.ID = TABLE1.FKID
AND VALUE5 NOT IN
 (SELECT VALUE FROM TABLE3 WHERE DISCR <> '0') 
AND VALUE3 = 'VAL' 
AND VALUE4 IN ('VAL','VAL2') 
AND TABLE1.VALUE1 <> 'TEST2' 
UNION 
SELECT 
TABLE1.ID, TABLE1.VALUE2 
FROM 
TABLE1, TABLE2 
WHERE TABLE2.ID = TABLE1.FKID 
AND TABLE1.VALUE1 = 'TEST2' 
ORDER BY 1 ASC

SELECT 
TABLE1.ID, 
(CASE TABLE1.VALUE1 WHEN 'TEST2' THEN TABLE1.VALUE2 ELSE TABLE1.VALUE1 END) 
FROM TABLE1, TABLE2 
WHERE TABLE2.ID = TABLE1.FKID 
AND ((TABLE1.VALUE1 = 'TEST2') 
OR (TABLE1.VALUE1 <> 'TEST2' 
AND VALUE5 NOT IN (SELECT VALUE FROM TABLE3 WHERE DISCR <> '0') 
AND VALUE3 = 'VAL' 
AND VALUE4 IN ('VAL','VAL2'))) ORDER BY 1 ASC